name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  emulatorSystemImage: system-images;android-35;google_apis;x86_64
  emulatorDevice: pixel_4
  emulatorName: integration_test
  emulatorPort: 5554
  simulatorOs: iOS-17-5
  simulatorDevice: iPhone 15

jobs:
  android-integration-test:
    runs-on: ubuntu-22.04
    steps:
      # Necessary so that the emulator can run with hardware acceleration.
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Add Android tools to PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Accept Android SDK licenses
        run: yes Y | sdkmanager --licenses

      - name: Install platform tools
        run: sdkmanager platform-tools

      - name: Install emulator
        run: sdkmanager emulator

      - name: Install system image
        run: sdkmanager "${{ env.emulatorSystemImage }}"

      - name: Create emulator
        run: |
          avdmanager create avd \
            --name "${{ env.emulatorName }}" \
            --package "${{ env.emulatorSystemImage }}" \
            --device "${{ env.emulatorDevice }}"

      - name: Start emulator
        run: |
          emulator \
            -avd "${{ env.emulatorName }}" \
            -port "${{ env.emulatorPort }}" \
            -no-window \
            -no-audio \
            -no-boot-anim \
            -partition-size 4096 \
            >./emulator-logs.txt 2>&1 &

          sleep 10
          cat ./emulator-logs.txt

      - name: Wait for emulator
        timeout-minutes: 2
        run: adb -s "emulator-${{ env.emulatorPort }}" wait-for-device

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      # Using this action greatly speeds up the build process through caching of dependencies
      # and build artifacts.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          pub-cache-key: |
            flutter-pub-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.*') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run intergration tests
        run: |
          flutter test integration_test --device-id "emulator-${{ env.emulatorPort }}"

      - name: Print emulator logs
        if: failure()
        run: cat ./emulator-logs.txt

  ios-integration-test:
    runs-on: macos-14
    steps:
      - name: Find simulator ID
        id: find_simulator_id
        run: |
          ID=$(
            xcrun simctl list -j |
            jq \
              ".devices[\"com.apple.CoreSimulator.SimRuntime.${{ env.simulatorOs }}\"] \
                  | map(select(.name == \"${{ env.simulatorDevice }}\"))
                  | first" |
            jq -r '.udid'
          )
          echo "ID=$ID" >> $GITHUB_OUTPUT

      - name: Boot simulator
        run: |
          xcrun simctl bootstatus "${{ steps.find_simulator_id.outputs.ID }}" -b

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          pub-cache-key: |
            flutter-pub-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.*') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run intergration tests
        run: |
          flutter test integration_test --device-id "${{ steps.find_simulator_id.outputs.ID }}"
